import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Registerior: Inventory Management System</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="#">Registerior</a>
        </h1>

        <p className={styles.description}>We are coming soon!</p>
      </main>

      <footer className={styles.footer}>
        <p>&copy; 2022 Kashinnov.com</p>
      </footer>
    </div>
  );
}
